// <auto-generated />
using System;
using ActorWebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ActorWebApi.Migrations
{
    [DbContext(typeof(SakilaContext))]
    [Migration("20230421072944_Creation")]
    partial class Creation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("ActorWebApi.Models.City", b =>
                {
                    b.Property<ushort>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("city_id");

                    b.Property<string>("City1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("city");

                    b.Property<ushort>("CountryId")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("LastUpdate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("last_update")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CityId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryId" }, "idx_fk_country_id");

                    b.ToTable("city", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
