// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdfHandlingPractice.Models;

#nullable disable

namespace PdfHandlingPractice.Migrations
{
    [DbContext(typeof(pdfHandlerContext))]
    partial class pdfHandlerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PdfHandlingPractice.Models.pdfFiles", b =>
                {
                    b.Property<int>("ResumeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("VenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("ResumeID");

                    b.ToTable("PdfFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
