// <auto-generated />
using CitiesDbImplementation.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CitiesDbImplementation.Migrations
{
    [DbContext(typeof(CityDbContext))]
    [Migration("20230402113155_once again")]
    partial class onceagain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CitiesDbImplementation.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"), 1L, 1);

                    b.Property<string>("CityCapital")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CityId");

                    b.ToTable("AllCities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityCapital = "Delhi",
                            CityName = "Delhi"
                        },
                        new
                        {
                            CityId = 2,
                            CityCapital = "Goregaon",
                            CityName = "Mumbai"
                        },
                        new
                        {
                            CityId = 4,
                            CityCapital = "Rasulgarh",
                            CityName = "Bhubaneswar"
                        });
                });

            modelBuilder.Entity("CitiesDbImplementation.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("InterestId");

                    b.HasIndex("CityId");

                    b.ToTable("AllInterests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            CityId = 1,
                            Description = "Red Fort"
                        },
                        new
                        {
                            InterestId = 2,
                            CityId = 1,
                            Description = "India Gate"
                        },
                        new
                        {
                            InterestId = 3,
                            CityId = 1,
                            Description = "Qutub Minar"
                        },
                        new
                        {
                            InterestId = 4,
                            CityId = 2,
                            Description = "Aksa Beach"
                        },
                        new
                        {
                            InterestId = 5,
                            CityId = 2,
                            Description = "Dana Pani Beach"
                        },
                        new
                        {
                            InterestId = 6,
                            CityId = 2,
                            Description = "CSMT"
                        },
                        new
                        {
                            InterestId = 7,
                            CityId = 4,
                            Description = "Planetorium"
                        },
                        new
                        {
                            InterestId = 8,
                            CityId = 4,
                            Description = "Science Park"
                        },
                        new
                        {
                            InterestId = 9,
                            CityId = 4,
                            Description = "Dhauli Giri"
                        });
                });

            modelBuilder.Entity("CitiesDbImplementation.Models.Interest", b =>
                {
                    b.HasOne("CitiesDbImplementation.Models.City", null)
                        .WithMany("Interests")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CitiesDbImplementation.Models.City", b =>
                {
                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
